title: Riley Ramone 
description: Riley Ramone is a web developer, pixel junkie, ticket scientist and leisure pirate.
markdown: kramdown
header_pages:
  - index.md
  - about.md
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/rillus" }
    - { platform: mastodon, user_url: "https://indieweb.social/@riley" }
    - { platform: twitter, user_url: "https://twitter.com/rillus" }